name: Static Analysis
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: on

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.x'     

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        
    - name: Get static analysis tools
      run: |
        go get golang.org/x/tools/cmd/goimports                               
        go get github.com/fzipp/gocyclo/cmd/gocyclo
        go get golang.org/x/lint/golint
        go get honnef.co/go/tools/cmd/staticcheck
        go get github.com/securego/gosec/v2/cmd/gosec

    - name: Vet
      run: go vet ./...

    - name: Goimports
      run: test -z $(goimports -e -d . | tee /dev/stderr)

    - name: Gocyclo
      run: gocyclo -over 20 .

    - name: Golint
      run: golint -set_exit_status $(go list ./...)

    - name: Staticcheck
      run: staticcheck -f stylish ./...

    - name: Gosec
      run: gosec ./...
