name: Static Analysis
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.5.0
      with:
        go-version: '1.16.x'     

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        
    - name: Get static analysis tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
        go install honnef.co/go/tools/cmd/staticcheck@v0.1.2
        go install github.com/securego/gosec/v2/cmd/gosec@v2.7.0

    - name: Vet
      run: go vet ./...

    - name: Goimports
      run: test -z $(goimports -e -d . | tee /dev/stderr)

    - name: Gocyclo
      run: gocyclo -over 20 .

    - name: Golint
      run: golint -set_exit_status $(go list ./...)

    - name: Staticcheck
      run: staticcheck -go 1.14 -f stylish ./...

    - name: Gosec
      run: gosec ./...
